services:
  db:
    image: postgres:16
    container_name: mi_postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: mi_base_de_datos
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups

  backup:
    build: ./backup
    container_name: postgres_backup
    restart: always
    depends_on:
      - db
    volumes:
      - ./backups:/backups
    command: sh -c "/usr/local/bin/backup.sh daily && cron && tail -f /var/log/cron.log"
    environment:
      PGPASSWORD: password123

volumes:
 postgres_data: